// NCAA Division I schools (alphabetical)
export const COLLEGES: string[] = [
  "Abilene Christian","Air Force","Akron","Alabama","Alabama A&M","Alabama State","Albany","Alcorn State",
  "American","Appalachian State","Arizona","Arizona State","Arkansas","Arkansas State","Arkansas–Pine Bluff",
  "Army West Point","Auburn","Austin Peay",
  "Ball State","Baylor","Belmont","Bellarmine","Bethune–Cookman","Binghamton","Boise State","Boston College",
  "Boston University","Bowling Green","Bradley","Brigham Young (BYU)","Brown","Bryant","Bucknell","Buffalo","Butler",
  "Cal Poly","Cal State Bakersfield","Cal State Fullerton","California Baptist","Campbell","Canisius",
  "Central Arkansas","Central Connecticut State","Central Michigan","Charleston","Charleston Southern",
  "Charlotte","Chattanooga","Chicago State","Cincinnati","Clemson","Cleveland State","Coastal Carolina",
  "Colgate","Colorado","Colorado State","Columbia","Connecticut","Coppin State","Cornell","Creighton","CSUN",
  "Dartmouth","Davidson","Dayton","Delaware","Delaware State","Denver","DePaul","Detroit Mercy","Drake","Drexel",
  "Duke","Duquesne",
  "East Carolina","Eastern Illinois","Eastern Kentucky","Eastern Michigan","Eastern Washington","Elon","Evansville",
  "Fairfield","Fairleigh Dickinson","Florida","Florida A&M","Florida Atlantic (FAU)","Florida Gulf Coast (FGCU)",
  "Florida International","Fordham","Fresno State","Furman",
  "Gardner–Webb","George Mason","George Washington","Georgetown","Georgia","Georgia Southern","Georgia State",
  "Georgia Tech","Gonzaga","Grand Canyon","Grambling State","Green Bay",
  "Hampton","Harvard","Hawai'i","High Point","Hofstra","Holy Cross","Houston","Houston Christian","Howard",
  "Idaho","Idaho State","Illinois","Illinois State","Incarnate Word","Indiana","Indiana State","Iona","Iowa",
  "Iowa State","IUPUI",
  "Jackson State","Jacksonville","Jacksonville State","James Madison","Kansas","Kansas City","Kansas State",
  "Kennesaw State","Kent State","Kentucky",
  "La Salle","Lafayette","Lamar","Le Moyne","Lehigh","Liberty","Lindenwood","LIU","Little Rock",
  "Long Beach State","Longwood","Louisiana","Louisiana Tech","Louisiana–Monroe","Louisville",
  "Loyola (MD)","Loyola Chicago","Loyola Marymount","LSU","Lipscomb",
  "Maine","Manhattan","Marist","Marquette","Marshall","Maryland","Maryland Eastern Shore","Massachusetts",
  "McNeese","Memphis","Mercer","Merrimack","Miami (FL)","Miami (OH)","Michigan","Michigan State","Middle Tennessee",
  "Milwaukee","Minnesota","Mississippi State","Mississippi Valley State","Missouri","Missouri State","Monmouth (NJ)",
  "Montana","Montana State","Morehead State","Morgan State","Mount St. Mary's","Murray State",
  "Navy","NC State","Nebraska","Nevada","New Hampshire","New Mexico","New Mexico State","New Orleans",
  "Niagara","Nicholls","NJIT","Norfolk State","North Alabama","North Carolina","North Dakota","North Dakota State",
  "North Florida","North Texas","Northeastern","Northern Arizona","Northern Colorado","Northern Illinois",
  "Northern Iowa","Northwestern","Northwestern State","Notre Dame",
  "Oakland","Ohio","Ohio State","Oklahoma","Oklahoma State","Old Dominion","Ole Miss","Omaha","Oral Roberts",
  "Oregon","Oregon State",
  "Pacific","Penn","Penn State","Pepperdine","Pittsburgh","Portland","Portland State","Prairie View A&M",
  "Presbyterian","Princeton","Providence","Purdue","Purdue Fort Wayne",
  "Queens (NC)","Quinnipiac",
  "Radford","Rhode Island","Rice","Richmond","Rider","Robert Morris","Rutgers",
  "Sacramento State","Sacred Heart","Saint Francis (PA)","Saint Joseph's","Saint Louis","Saint Mary's (CA)",
  "Saint Peter's","Sam Houston","Samford","San Diego State","San Jose State","Santa Clara","Seattle U",
  "Seton Hall","Siena","SIU Edwardsville","SMU","South Alabama","South Carolina","South Carolina State",
  "South Dakota","South Dakota State","South Florida","Southeastern Louisiana","Southern (LA)","Southern Illinois",
  "Southern Miss","Southern Utah","St. Bonaventure","St. John's","St. Thomas (MN)","Stanford","Stephen F. Austin",
  "Stetson","Stonehill","Syracuse",
  "TCU","Temple","Tennessee","Tennessee State","Tennessee Tech","Texas","Texas A&M","Texas A&M–Commerce",
  "Texas A&M–Corpus Christi","Texas State","Texas Tech","The Citadel","Toledo","Towson","Troy","Tulane","Tulsa",
  "UAB","UC Davis","UC Irvine","UC Riverside","UC San Diego","UC Santa Barbara","UCF","UCLA","UIC",
  "UMass Lowell","UNLV","USC","USC Upstate","UT Arlington","UTEP","UT Martin","UTRGV","UTSA","Utah","Utah State",
  "Utah Tech","Utah Valley",
  "Valparaiso","Vanderbilt","VCU","Vermont","Villanova","Virginia","Virginia Tech","VMI",
  "Wagner","Wake Forest","Washington","Washington State","Weber State","West Virginia","Western Carolina",
  "Western Illinois","Western Kentucky","Western Michigan","Wichita State","William & Mary","Winthrop",
  "Wisconsin","Wofford","Wright State","Wyoming",
  "Xavier",
  "Yale","Youngstown State"
];
