// Countries that have produced at least one NBA or NFL player (USA excluded).
// Alphabetical for nicer UX.
export const COUNTRIES: string[] = [
  // Africa
  "Angola",
  "Cameroon",
  "Central African Republic",
  "Côte d’Ivoire",
  "Egypt",
  "Gabon",
  "Ghana",
  "Liberia",
  "Mali",
  "Nigeria",
  "Senegal",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tunisia",
  "Zimbabwe",

  // Americas (non‑USA)
  "Argentina",
  "Bahamas",
  "Brazil",
  "Canada",
  "Cuba",
  "Dominican Republic",
  "Jamaica",
  "Mexico",
  "Puerto Rico",
  "Venezuela",

  // Asia
  "China",
  "India",
  "Iran",
  "Israel",
  "Japan",
  "South Korea",
  "Taiwan",

  // Europe
  "Austria",
  "Belgium",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Croatia",
  "Czechia",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Hungary",
  "Ireland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Montenegro",
  "Netherlands",
  "North Macedonia",
  "Norway",
  "Poland",
  "Romania",
  "Russia",
  "Serbia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
  "United Kingdom",

  // Oceania
  "Australia",
  "New Zealand",
].sort((a, b) => a.localeCompare(b));
